version: '3'

name: task

services:
  mysql:
    container_name: mysql
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - main
    restart: always

networks:
  main:
